#!/usr/bin/env node
/**
 * Mints a signed offline license key using private-key.json (generated by
 * keygen.js). Run this on your own machine — it never touches a network,
 * and the private key never has to leave this directory.
 *
 * Usage:
 *   node licensing/mint.js --tier=offline-pro --licensee="Springfield Library" [--seats=50] [--expires=2027-12-31]
 *
 * The output is the license key string to hand to the buyer. They paste it
 * into Dockbench's "Enter a license key" panel, which verifies it entirely
 * offline via the public key already embedded in the app — no server
 * round-trip, ever, on either side.
 */
const fs = require('fs');
const path = require('path');
const { webcrypto } = require('crypto');

const PRIVATE_PATH = path.join(__dirname, 'private-key.json');

function parseArgs(argv) {
  const out = {};
  for (const arg of argv) {
    const m = arg.match(/^--([\w-]+)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function b64url(bytes) {
  return Buffer.from(bytes).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function main() {
  if (!fs.existsSync(PRIVATE_PATH)) {
    console.error(`No private key found at ${PRIVATE_PATH}.`);
    console.error('Run `node licensing/keygen.js` first.');
    process.exit(1);
  }
  const args = parseArgs(process.argv.slice(2));
  if (!args.tier) {
    console.error('Required: --tier=<name>  (e.g. offline-pro)');
    console.error('Optional: --licensee="Name", --seats=N, --expires=YYYY-MM-DD');
    process.exit(1);
  }

  const privateJwk = JSON.parse(fs.readFileSync(PRIVATE_PATH, 'utf8'));
  const privateKey = await webcrypto.subtle.importKey(
    'jwk', privateJwk, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign']
  );

  const payload = {
    tier: args.tier,
    licensee: args.licensee || null,
    seats: args.seats ? parseInt(args.seats, 10) : 1,
    issued: new Date().toISOString().slice(0, 10),
    expires: args.expires || null, // null = perpetual license
  };

  const payloadB64 = b64url(Buffer.from(JSON.stringify(payload), 'utf8'));
  const signature = await webcrypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' },
    privateKey,
    Buffer.from(payloadB64, 'utf8')
  );
  const licenseKey = payloadB64 + '.' + b64url(signature);

  console.log('License payload:', JSON.stringify(payload, null, 2));
  console.log('');
  console.log('License key (give this to the buyer):');
  console.log(licenseKey);
}

main().catch(e => { console.error(e); process.exit(1); });
