/* Generated by scripts/build-downloads.py — do not edit.
 * Release: unknown
 * Baked in at build time so download.html works offline and makes
 * no third-party request on load. */
window.DOCKBENCH_RELEASES = {
  "play": {
    "url": "https://play.google.com/store/apps/details?id=in.co.pdflove"
  },
  "windows_msi": {
    "url": "https://github.com/hellomrsys-maker/Dockbench/releases/latest"
  },
  "windows_exe": {
    "url": "https://github.com/hellomrsys-maker/Dockbench/releases/latest"
  },
  "macos_arm": {
    "url": "https://github.com/hellomrsys-maker/Dockbench/releases/latest"
  },
  "macos_x64": {
    "url": "https://github.com/hellomrsys-maker/Dockbench/releases/latest"
  },
  "linux_appimage": {
    "url": "https://github.com/hellomrsys-maker/Dockbench/releases/latest"
  },
  "linux_deb": {
    "url": "https://github.com/hellomrsys-maker/Dockbench/releases/latest"
  },
  "android_apk": {
    "url": "https://github.com/hellomrsys-maker/Dockbench/releases/latest"
  }
};
