#!/usr/bin/env python3
"""
Generate frontend/downloads.js — the release-asset table download.html reads.

    python scripts/build-downloads.py [--tag v1.2.3]

Why a build step rather than fetching the GitHub API from the page:

  * download.html has to work offline, like the rest of the app. A runtime
    fetch would leave the page blank for an installed/offline visitor.
  * It would also be an outbound request to a third party on page load,
    which contradicts the network contract the whole product is built on.

Run in CI after the release workflow uploads its assets. If the API is
unreachable, this writes a file whose entries fall back to the releases
page rather than failing the build.
"""

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request

REPO = os.environ.get("GITHUB_REPOSITORY", "hellomrsys-maker/Dockbench")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "frontend", "downloads.js")
RELEASES_PAGE = f"https://github.com/{REPO}/releases/latest"

# asset filename pattern -> key used by download.html
PATTERNS = [
    ("windows_msi",    r"\.msi$"),
    ("windows_exe",    r"-setup\.exe$|\.exe$"),
    ("macos_arm",      r"aarch64.*\.dmg$|arm64.*\.dmg$"),
    ("macos_x64",      r"x64.*\.dmg$|x86_64.*\.dmg$|\.dmg$"),
    ("linux_appimage", r"\.AppImage$"),
    ("linux_deb",      r"\.deb$"),
    ("android_apk",    r"\.apk$"),
]


def fetch_release(tag=None):
    url = (f"https://api.github.com/repos/{REPO}/releases/tags/{tag}" if tag
           else f"https://api.github.com/repos/{REPO}/releases/latest")
    req = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "User-Agent": "dockbench-build",
    })
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.load(r)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", help="release tag; defaults to the latest release")
    args = ap.parse_args()

    entries = {}
    version = ""
    try:
        rel = fetch_release(args.tag)
        version = rel.get("tag_name", "")
        assets = rel.get("assets", [])
        print(f"release {version}: {len(assets)} assets")

        for key, pattern in PATTERNS:
            if key in entries:
                continue
            for a in assets:
                if re.search(pattern, a["name"], re.I):
                    entries[key] = {
                        "url": a["browser_download_url"],
                        "name": a["name"],
                        "size": a["size"],
                        "version": version,
                    }
                    print(f"  {key:16} {a['name']}")
                    break

        # Checksums, if the release publishes them.
        for a in assets:
            if re.search(r"(checksums|SHA256SUMS)", a["name"], re.I):
                try:
                    with urllib.request.urlopen(a["browser_download_url"], timeout=20) as r:
                        sums = r.read().decode()
                    for e in entries.values():
                        m = re.search(rf"^([0-9a-f]{{64}})\s+\*?{re.escape(e['name'])}$",
                                      sums, re.M | re.I)
                        if m:
                            e["sha256"] = m.group(1)
                except urllib.error.URLError:
                    pass
                break

    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError) as e:
        # Not fatal: the page falls back to the releases URL for every entry.
        print(f"warning: could not reach the GitHub API ({e}); "
              "writing fallbacks only", file=sys.stderr)

    entries.setdefault("play", {
        "url": "https://play.google.com/store/apps/details?id=app.dockbench.twa"})

    for key, _ in PATTERNS:
        entries.setdefault(key, {"url": RELEASES_PAGE})

    body = (
        "/* Generated by scripts/build-downloads.py — do not edit.\n"
        f" * Release: {version or 'unknown'}\n"
        " * Baked in at build time so download.html works offline and makes\n"
        " * no third-party request on load. */\n"
        "window.DOCKBENCH_RELEASES = " + json.dumps(entries, indent=2) + ";\n"
    )
    with open(OUT, "w") as f:
        f.write(body)
    print(f"wrote {OUT} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
